"""Test vectors for the Swift port (§1.9): every public pure function on synthetic inputs, with the
outputs the spike gives. `make vectors` rewrites tests/vectors/*.json from this file, and
`test_vectors.py` fails while they are stale, e.g. after the §1.8 sweep moves a default.

One file per module: {"_": note, "constants": {NAME: value}, "cases": [{"name", "fn", "args",
"expected" or "raises"}]}.

- `fn` is `module.function`, or `module.Class.method` with `self` among the args. `pipeline` is
  the whole spike on one couple (`pipeline` below).
- `args` names every parameter, defaults included, so no case leans on the port's defaults.
  `constants` holds the module's own constants, so the port can check its values against them.
- A dataclass is an object of its fields. Two arg types are built, not read: a CommuteBuffer
  from `commute_buffer`'s parameters, a Homes from `Homes.of`'s.
- bytes (salts, hashes) are lowercase hex. A frozenset is a list sorted by each item's JSON:
  compare it as a set. In an output, a photo is its asset_id.
- `raises` names the exception class in place of an output.
- Floats are written exactly. Compare them to within 1e-9: the port may sum in another order.
"""

from __future__ import annotations

import ast
import datetime as dt
import importlib
import inspect
import json
import math
import types
import typing
from collections.abc import Callable, Iterable, Sequence
from dataclasses import fields, is_dataclass, replace
from pathlib import Path
from typing import Any, NewType

import pygeohash as pgh

from photoquiz import (
    anchors,
    buckets,
    commute,
    filters,
    matching,
    project,
    synth,
    trips,
)
from photoquiz.models import (
    Anchors,
    BucketHash,
    BucketKey,
    Era,
    LatLon,
    PhotoMeta,
    TripWindow,
)

OUT = Path(__file__).resolve().parent / "vectors"
PURE = (project, filters, buckets, matching, commute, anchors, trips)
BUILT: dict[type, Callable[..., Any]] = {commute.CommuteBuffer: commute.commute_buffer, trips.Homes: trips.Homes.of}
NOTE = "Generated by spike/tests/vectorgen.py (`make vectors`), whose docstring gives the format. Do not edit."


# codec


def encode(v: Any, *, out: bool = False) -> Any:
    if v is None or isinstance(v, (bool, int, float, str)):
        return v
    if isinstance(v, bytes):
        return v.hex()
    if out and isinstance(v, PhotoMeta):
        return v.asset_id
    if is_dataclass(v):
        return {f.name: encode(getattr(v, f.name), out=out) for f in fields(v)}
    if isinstance(v, (set, frozenset)):
        return sorted((encode(x, out=out) for x in v), key=lambda x: json.dumps(x, sort_keys=True))
    if isinstance(v, (list, tuple, range)):
        return [encode(x, out=out) for x in v]
    if isinstance(v, dict):
        return {k: encode(x, out=out) for k, x in v.items()}
    raise TypeError(f"cannot encode {type(v).__name__}")


def decode(v: Any, tp: Any) -> Any:
    origin, targs = typing.get_origin(tp), typing.get_args(tp)
    if origin in (typing.Union, types.UnionType):
        [inner] = [t for t in targs if t is not type(None)]
        return None if v is None else decode(v, inner)
    if isinstance(tp, NewType):
        return decode(v, tp.__supertype__)
    if tp is bytes:
        return bytes.fromhex(v)
    if tp is float:
        return float(v)
    if tp in (int, str, bool):
        return v
    if tp in BUILT:
        return call(BUILT[tp], v)
    if is_dataclass(tp):
        hints = typing.get_type_hints(tp)
        return tp(**{k: decode(x, hints[k]) for k, x in v.items()})
    if origin is frozenset:
        return frozenset(decode(x, targs[0]) for x in v)
    if origin is tuple:
        return tuple(decode(x, t) for x, t in zip(v, targs, strict=True))
    if origin in (list, Sequence, Iterable):
        return [decode(x, targs[0]) for x in v]
    raise TypeError(f"cannot decode {tp}")


def qualname(fn: Callable[..., Any]) -> str:
    module = fn.__module__
    return f"{module.removeprefix('photoquiz.')}.{fn.__qualname__}" if module.startswith("photoquiz.") else fn.__name__


def resolve(name: str) -> Callable[..., Any]:
    if name == "pipeline":
        return pipeline
    module, *path = name.split(".")
    obj: Any = importlib.import_module(f"photoquiz.{module}")
    for part in path:
        obj = getattr(obj, part)
    return obj


def call(fn: Callable[..., Any], args: dict[str, Any]) -> Any:
    hints = typing.get_type_hints(fn)
    if "self" in inspect.signature(fn).parameters:
        hints["self"] = getattr(importlib.import_module(fn.__module__), fn.__qualname__.split(".")[0])
    return fn(**{k: decode(v, hints[k]) for k, v in args.items()})


def run(c: dict[str, Any]) -> dict[str, Any]:
    """A case's outcome, from its JSON alone: what the port does."""
    try:
        return {"expected": encode(call(resolve(c["fn"]), c["args"]), out=True)}
    except ValueError as e:
        return {"raises": type(e).__name__}


def bound(fn: Callable[..., Any], *args: Any, **kw: Any) -> dict[str, Any]:
    b = inspect.signature(fn).bind(*args, **kw)
    b.apply_defaults()
    return dict(b.arguments)


def case(name: str, fn: Callable[..., Any], **kw: Any) -> dict[str, Any]:
    c = {"name": name, "fn": qualname(fn), "args": encode(bound(fn, **kw))}
    return c | run(c)


def buf(home: LatLon, work: LatLon | None = None, km: float = commute.BUFFER_KM) -> dict[str, Any]:
    """A CommuteBuffer arg, as the parameters that build it."""
    return bound(commute.commute_buffer, home, work, km)


def homes(a: Anchors, b: Anchors, **kw: Any) -> dict[str, Any]:
    """A Homes arg, as the parameters that build it."""
    return bound(trips.Homes.of, a, b, **kw)


def constants(module: types.ModuleType) -> dict[str, Any]:
    """The upper-case names the module assigns itself, not the ones it imports."""
    names = []
    for node in ast.parse(inspect.getsource(module)).body:
        targets = (
            node.targets if isinstance(node, ast.Assign) else [node.target] if isinstance(node, ast.AnnAssign) else []
        )
        names += [t.id for t in targets if isinstance(t, ast.Name) and t.id.isupper()]
    return {n: encode(getattr(module, n)) for n in names}


def dumps(v: Any, depth: int = 0) -> str:
    """JSON with a short or flat container on one line (a photo, a key), anything else broken up."""
    flat = json.dumps(v)
    children = list(v.values()) if isinstance(v, dict) else v if isinstance(v, list) else []
    if (
        not children
        or len(flat) <= 100
        or (len(flat) <= 400 and not any(isinstance(c, (dict, list)) for c in children))
    ):
        return flat
    pad = "  " * (depth + 1)
    if isinstance(v, dict):
        lines = [f"{pad}{json.dumps(k)}: {dumps(x, depth + 1)}" for k, x in v.items()]
        return "{\n" + ",\n".join(lines) + "\n" + "  " * depth + "}"
    return "[\n" + ",\n".join(pad + dumps(x, depth + 1) for x in v) + "\n" + "  " * depth + "]"


# fixtures: made-up people in real places, as in the unit tests

HOME = LatLon(37.7600, -122.4400)
WORK = LatLon(37.7900, -122.4000)
BAR = LatLon(37.7700, -122.4200)
B_HOME = LatLon(37.4430, -122.1610)  # 43 km from HOME
IN_TOWN = LatLon(37.8044, -122.2712)  # Oakland: past the 5 km buffers, inside the 25 km city
NAPA = LatLon(38.2975, -122.2869)  # out of town
TAHOE = LatLon(39.0968, -120.0324)
TAHOE_2 = LatLon(39.0500, -120.1000)  # another cell, ~7 km away
OLD_CITY = LatLon(47.6062, -122.3321)  # a home before HOME, ~1,100 km away
OLD, OLD_WORK = LatLon(40.7300, -73.9950), LatLon(40.7550, -73.9850)  # a home on the other coast
FAR = LatLon(21.3000, -157.8500)  # a long stay away
NYC = LatLon(40.7128, -74.0060)

PDT, PST, JST, HST, EDT = -7 * 3600, -8 * 3600, 9 * 3600, -10 * 3600, -4 * 3600
SALT = bytes(range(32))
T0 = 1_783_710_000  # 2026-07-10 19:00Z, a Friday, exactly on an hour boundary
H = T0 // 3600
FRI = dt.date(2026, 10, 2)
THU, SAT, SUN = FRI - dt.timedelta(days=1), FRI + dt.timedelta(days=1), FRI + dt.timedelta(days=2)
MOVED = dt.date(2026, 8, 1)


def photo(asset_id: str, utc: int | None, at: LatLon | None = TAHOE, *, tz: int | None = PDT, **kw: Any) -> PhotoMeta:
    """No camera make or model, as in every iOS export (§1.2a)."""
    lat, lon = (None, None) if at is None else (at.lat, at.lon)
    return replace(PhotoMeta(asset_id, utc, tz, lat, lon, False, None, False, None, None, 4032, 3024), **kw)


def local(day: dt.date, hour: float, at: LatLon | None = HOME, tz: int = PDT, plus: int = 0) -> PhotoMeta:
    """A photo at wall-clock `hour` on local `day`, `plus` seconds later."""
    midnight = int(dt.datetime(day.year, day.month, day.day, tzinfo=dt.UTC).timestamp())
    utc = midnight + round(hour * 3600) - tz + plus
    return photo(f"p{utc}", utc, at, tz=tz)


def utc_at(day: dt.date, hour: float, tz: int) -> PhotoMeta:
    """A photo at `hour` UTC on `day`, taken where the offset is `tz`."""
    return replace(local(day, hour, tz=0), tz_offset_s=tz)


def days_before(day: dt.date, n: int) -> list[dt.date]:
    return [day - dt.timedelta(days=i) for i in range(n)]


def weekdays_before(day: dt.date, n: int) -> list[dt.date]:
    return [d for d in days_before(day, 2 * n) if d.weekday() < 5][:n]


def nights(spot: LatLon, first: dt.date, last: dt.date, every: int = 2, tz: int = PDT) -> list[PhotoMeta]:
    """A photo at 02:00 local every `every` days from first to last."""
    return [local(first + dt.timedelta(days=d), 2.0, spot, tz) for d in range(0, (last - first).days + 1, every)]


def cell(p: LatLon, precision: int = 6) -> str:
    return pgh.encode(p.lat, p.lon, precision=precision)


def centre(gh: str) -> LatLon:
    c = pgh.decode(gh)
    return LatLon(c.latitude, c.longitude)


def right(gh: str, n: int = 1) -> str:
    for _ in range(n):
        gh = pgh.get_adjacent(gh, "right")
    return gh


def key(p: LatLon, hour: int) -> BucketKey:
    return BucketKey(cell(p), hour)


def shots(person: str, n: int, hour: int = H) -> list[PhotoMeta]:
    return [photo(f"{person}-{i}", hour * 3600 + 600 + i) for i in range(n)]


def hours(person: str, *hs: int, where: LatLon | None = TAHOE) -> list[PhotoMeta]:
    """A photo at the start of each hour H + h."""
    return [photo(f"{person}-{h}", (H + h) * 3600, where) for h in hs]


def anchored(person: str, home: LatLon, work: LatLon | None = None, shared_home: bool | None = None) -> Anchors:
    return Anchors(person, home, work, cell(home, 7), None if work is None else cell(work, 7), 90, 10, 0, shared_home)


SHARED = anchored("a", HOME, WORK), anchored("b", HOME)
APART = anchored("a", HOME), anchored("b", B_HOME)
MOVE = H + 1000  # an hour index; H and the days after it come before the move


def lived(then_a: LatLon = OLD_CITY, then_b: LatLon = OLD_CITY, now: tuple[Anchors, Anchors] = SHARED) -> dict:
    """Each partner's eras: a past home until MOVE, then their anchors' home."""
    return {
        f"eras_{x.person}": [Era(None, then, None, True, 30), Era(MOVE * 3600, x.home, x.work, False, 30)]
        for x, then in zip(now, (then_a, then_b))
    }


# cases, one function per file


def project_cases() -> list[dict]:
    return [
        case("the origin is (0, 0)", project.to_km, p=HOME, origin=HOME),
        case("a degree north", project.to_km, p=LatLon(HOME.lat + 1, HOME.lon), origin=HOME),
        case("a 43 km commute", project.to_km, p=B_HOME, origin=HOME),
        case(
            "across the antimeridian, the short way", project.to_km, p=LatLon(0.0, -179.99), origin=LatLon(0.0, 179.99)
        ),
        case("south of the equator", project.to_km, p=LatLon(-33.8688, 151.2093), origin=LatLon(-33.9, 151.0)),
        case("a point to itself", project.distance_km, a=HOME, b=HOME),
        case("home to work", project.distance_km, a=HOME, b=WORK),
        case("across the antimeridian", project.distance_km, a=LatLon(0.0, 179.99), b=LatLon(0.0, -179.99)),
    ]


def buckets_cases() -> list[dict]:
    bb = pgh.get_bounding_box("9q8yyk")
    lon = bb.min_lon + 0.001

    def at(lat: float, lon: float) -> PhotoMeta:
        return photo("P-1", T0, LatLon(lat, lon))

    out = [
        case("on an hour boundary", buckets.bucket_key, p=photo("P-1", T0)),
        case("a second before the hour", buckets.bucket_key, p=photo("P-1", T0 - 1)),
        case("before 1970: floor division", buckets.bucket_key, p=photo("P-1", -1)),
        case("a cell holds its south-west corner", buckets.bucket_key, p=at(bb.min_lat, bb.min_lon)),
        case("its north edge is the next cell up", buckets.bucket_key, p=at(bb.max_lat, bb.min_lon)),
        case("half a metre below the north edge", buckets.bucket_key, p=at(bb.max_lat - 0.000005, lon)),
        case("half a metre above it", buckets.bucket_key, p=at(bb.max_lat + 0.000005, lon)),
        case("at longitude -180", buckets.bucket_key, p=at(0.0, -180.0)),
        case("just west of longitude +180", buckets.bucket_key, p=at(0.0, 179.9999)),
        case("near the north pole", buckets.bucket_key, p=at(89.9999, 10.0)),
        case("no GPS: no key", buckets.bucket_key, p=photo("P-1", T0, None)),
        case("no timestamp: no key", buckets.bucket_key, p=photo("P-1", None)),
        case("geohash precision 5", buckets.bucket_key, p=photo("P-1", T0), precision=5),
        case("geohash precision 7", buckets.bucket_key, p=photo("P-1", T0), precision=7),
        case("self and 8 neighbours, x 3 hours", buckets.expand, k=BucketKey("9q8yyk", H)),
        case("wraps the antimeridian eastward", buckets.expand, k=BucketKey("800000", H)),
        case("wraps the antimeridian westward", buckets.expand, k=BucketKey("xbpbpb", H)),
        case("the north pole has no row above: 18 keys", buckets.expand, k=BucketKey("zzzzzz", H)),
        case("the south pole has no row below: 18 keys", buckets.expand, k=BucketKey("000000", H)),
        case("HMAC-SHA256 of 'geohash|hour', first 16 bytes", buckets.salted, k=BucketKey("9qfwkt", H), salt=SALT),
        case("a negative hour", buckets.salted, k=BucketKey("9qfwkt", -1), salt=SALT),
        case("a geohash-5 key", buckets.salted, k=BucketKey("9qfwk", H), salt=SALT),
        case("another salt", buckets.salted, k=BucketKey("9qfwkt", H), salt=bytes(32)),
        case("a 31-byte salt is refused", buckets.salted, k=BucketKey("9qfwkt", H), salt=bytes(31)),
        case("a set of keys", buckets.salted_set, ks=[key(TAHOE, H), key(NAPA, H + 1)], salt=SALT),
    ]
    ps = [photo("t-1", T0), photo("t-2", T0 + 60), photo("no-gps", T0, None), photo("napa", T0 + 7200, NAPA)]
    out += [
        case("raw: one key per bucket, none without GPS", buckets.own_keys, ps=ps, expanded=False),
        case("expanded (side A only)", buckets.own_keys, ps=ps, expanded=True),
        case("geohash precision 5", buckets.own_keys, ps=ps, expanded=False, precision=5),
    ]
    # One-sided matching: A expands, B stays raw, and each side maps the survivors back alone.
    x = "9q8yyk"

    def near(asset_id: str, gh: str, hour: int) -> PhotoMeta:
        return photo(asset_id, hour * 3600 + 600, centre(gh))

    ps_a = [near("a-near", x, H), near("a-far", right(x, 5), H)]
    ps_b = [near("b-near", right(x), H + 1), photo("b-no-gps", H * 3600 + 600, None), near("b-later", x, H + 3)]
    own_a, own_b = buckets.own_keys(ps_a, expanded=True), buckets.own_keys(ps_b, expanded=False)
    m = matching.match(buckets.salted_set(own_a, SALT), buckets.salted_set(own_b, SALT))
    keys = buckets.matched_keys(own_a, m, SALT)
    return out + [
        case("A maps the survivors back from its expanded keys", buckets.matched_keys, own=own_a, matched=m, salt=SALT),
        case("B from its raw keys, to the same set", buckets.matched_keys, own=own_b, matched=m, salt=SALT),
        case("A keeps a photo whose neighbourhood matched", buckets.matched_photos, ps=ps_a, keys=keys, expanded=True),
        case("B keeps a photo whose own key matched", buckets.matched_photos, ps=ps_b, keys=keys, expanded=False),
    ]


def matching_cases() -> list[dict]:
    h = [BucketHash(bytes([i]) * 16) for i in range(4)]
    return [
        case("the intersection", matching.match, expanded_a=frozenset(h[:3]), raw_b=frozenset(h[1:])),
        case("nothing in common", matching.match, expanded_a=frozenset(h[:1]), raw_b=frozenset(h[1:])),
        case("one side empty", matching.match, expanded_a=frozenset(), raw_b=frozenset(h)),
    ]


def filters_cases() -> list[dict]:
    ps = [
        photo("plain", T0),
        photo("no-gps", T0 + 60, None),
        photo("screenshot", T0 + 120, is_screenshot=True),
        photo("no-time", None),
        photo("screenshot-in-b1", T0 + 180, is_screenshot=True, burst_id="b1"),  # counted as a screenshot
        photo("b1-early", T0 + 200, burst_id="b1"),
        photo("b1-pick", T0 + 400, burst_id="b1", is_burst_pick=True),  # the pick beats the earliest
        photo("b2-late", T0 + 900, burst_id="b2"),
        photo("b2-early", T0 + 800, burst_id="b2"),  # no pick: the earliest
        photo("b3-y", T0 + 1000, burst_id="b3"),
        photo("b3-x", T0 + 1000, burst_id="b3"),  # same time: the smaller asset_id
        photo("b4-no-time", None, burst_id="b4"),  # alone, a timed photo beats it
        photo("b4-timed", T0 + 1100, burst_id="b4"),
    ]
    return [
        case("screenshots", filters.drop_screenshots, ps=ps),
        case("missing timestamps", filters.drop_missing_timestamp, ps=ps),
        case("bursts: the pick, else the earliest timed, else the smallest asset_id", filters.collapse_bursts, ps=ps),
        case("all rules in order, each photo counted once", filters.apply_all, ps=ps),
        case("nothing to filter", filters.apply_all, ps=[]),
    ]


def off(origin: LatLon, x: float, y: float) -> LatLon:
    """The point (x east, y north) km from `origin` on its plane: the inverse of to_km."""
    return LatLon(
        origin.lat + y / project.KM_PER_DEG_LAT,
        origin.lon + x / (project.KM_PER_DEG_LON * math.cos(math.radians(origin.lat))),
    )


def covers(name: str, home: LatLon, work: LatLon | None, km: float, p: LatLon) -> dict:
    """A point at least 50 m from the buffer's edge, where shapely's polygon (at most 6 m inside the
    true circle) and the port's exact point-to-segment distance agree."""
    px, py = project.to_km(p, home)
    wx, wy = (0.0, 0.0) if work is None else project.to_km(work, home)
    t = max(0.0, min(1.0, (px * wx + py * wy) / (wx * wx + wy * wy))) if (wx or wy) else 0.0
    assert abs(math.hypot(px - t * wx, py - t * wy) - km) >= 0.05, name
    return case(name, commute.CommuteBuffer.covers, self=buf(home, work, km), p=p)


def commute_cases() -> list[dict]:
    wx, wy = project.to_km(WORK, HOME)
    length = math.hypot(wx, wy)
    ux, uy = wx / length, wy / length  # along the commute
    nx, ny = -uy, ux  # across it
    around = [
        ("home", 0.0, 0.0),
        ("work", wx, wy),
        ("4.9 km across the middle", wx / 2 + 4.9 * nx, wy / 2 + 4.9 * ny),
        ("5.1 km across the middle", wx / 2 + 5.1 * nx, wy / 2 + 5.1 * ny),
        ("4.9 km past work", wx + 4.9 * ux, wy + 4.9 * uy),
        ("5.1 km past work", wx + 5.1 * ux, wy + 5.1 * uy),
        ("4.9 km behind home", -4.9 * ux, -4.9 * uy),
        ("5.1 km behind home", -5.1 * ux, -5.1 * uy),
        ("4.9 km off work's corner", wx + 4.9 * (ux + nx) / math.sqrt(2), wy + 4.9 * (uy + ny) / math.sqrt(2)),
        ("5.1 km off work's corner", wx + 5.1 * (ux + nx) / math.sqrt(2), wy + 5.1 * (uy + ny) / math.sqrt(2)),
    ]
    out = [covers(f"commute buffer: {n}", HOME, WORK, commute.BUFFER_KM, off(HOME, x, y)) for n, x, y in around]
    out += [
        covers("no work: a disc, 4.9 km east", NYC, None, commute.BUFFER_KM, off(NYC, 4.9, 0.0)),
        covers("no work: a disc, 5.1 km south", NYC, None, commute.BUFFER_KM, off(NYC, 0.0, -5.1)),
        covers("work at home: a disc, 5.1 km north", HOME, HOME, commute.BUFFER_KM, off(HOME, 0.0, 5.1)),
        covers("a 43 km commute, halfway", HOME, B_HOME, commute.BUFFER_KM, LatLon(37.6015, -122.3005)),
        covers("home city: Oakland is in town", HOME, WORK, 25.0, IN_TOWN),
        covers("home city: Napa is out of town", HOME, WORK, 25.0, NAPA),
    ]
    home, work = LatLon(0.0, 179.99), LatLon(0.0, -179.97)  # work ~4.5 km east, across the line
    out += [
        covers(f"across the antimeridian: lon {lon}", home, work, commute.BUFFER_KM, LatLon(0.0, lon))
        for lon in (-179.95, 179.95, -179.90, 179.90)
    ]
    out += [
        case("homes 0.5 km apart are one", commute.is_shared_home, a=HOME, b=off(HOME, 0.5, 0.0)),
        case("homes 1.5 km apart are two", commute.is_shared_home, a=HOME, b=off(HOME, 0.0, 1.5)),
        case("across the antimeridian", commute.is_shared_home, a=LatLon(0.0, 179.999), b=LatLon(0.0, -179.999)),
    ]
    near, far = anchored("b", off(HOME, 0.3, 0.0)), anchored("b", B_HOME)
    out += [
        case("no override: by distance, near", commute.resolve_shared_home, a=anchored("a", HOME), b=near),
        case("no override: by distance, far", commute.resolve_shared_home, a=anchored("a", HOME), b=far),
        case(
            "told they share, though far", commute.resolve_shared_home, a=anchored("a", HOME, shared_home=True), b=far
        ),
        case(
            "told they don't, though near",
            commute.resolve_shared_home,
            a=anchored("a", HOME, shared_home=False),
            b=near,
        ),
        case(
            "the two files disagree",
            commute.resolve_shared_home,
            a=anchored("a", HOME, shared_home=True),
            b=replace(far, shared_home=False),
        ),
    ]
    a_buf, b_near, b_far = buf(HOME, WORK), buf(off(HOME, 2.0, 0.0)), buf(B_HOME)
    return out + [
        case(
            "shared home: inside a buffer is home", commute.is_away, p=WORK, buf_a=a_buf, buf_b=b_near, shared_home=True
        ),
        case(
            "shared home: outside both is away", commute.is_away, p=IN_TOWN, buf_a=a_buf, buf_b=b_near, shared_home=True
        ),
        case("different homes: a visit counts", commute.is_away, p=B_HOME, buf_a=a_buf, buf_b=b_far, shared_home=False),
        case("different homes: outside both", commute.is_away, p=NAPA, buf_a=a_buf, buf_b=b_far, shared_home=False),
        case(
            "different homes: inside both is home",
            commute.is_away,
            p=off(HOME, 1.0, 0.0),
            buf_a=a_buf,
            buf_b=b_near,
            shared_home=False,
        ),
    ]


def anchors_cases() -> list[dict]:
    out = [
        case("west of UTC: 03:00Z Fri is 20:00 Thu", anchors.local_hour, p=utc_at(FRI, 3.0, PDT)),
        case("west of UTC: the local day", anchors.local_day, p=utc_at(FRI, 3.0, PDT)),
        case("east of UTC: 20:00Z Fri is 05:00 Sat", anchors.local_hour, p=utc_at(FRI, 20.0, JST)),
        case("east of UTC: the local day", anchors.local_day, p=utc_at(FRI, 20.0, JST)),
        case("DST: 09:30Z in winter is 01:30", anchors.local_hour, p=utc_at(dt.date(2026, 1, 15), 9.5, PST)),
        case("DST: 09:30Z in summer is 02:30", anchors.local_hour, p=utc_at(dt.date(2026, 7, 15), 9.5, PDT)),
        case("before 1970: floor", anchors.local_hour, p=photo("p", -1, tz=0)),
        case("before 1970: day -1", anchors.local_day, p=photo("p", -1, tz=0)),
        case("no time zone: no local hour", anchors.local_hour, p=photo("p", T0, tz=None)),
        case("no time zone: no local day", anchors.local_day, p=photo("p", T0, tz=None)),
    ]
    out += [case(f"day {d}", anchors.weekday, day=d) for d in (-800, -1, 0, 1, 4, 20_728)]

    def infer(name: str, ps: list[PhotoMeta], **kw: Any) -> dict:
        kw.setdefault("now_utc", max(p.utc_epoch for p in ps))
        return case(name, anchors.infer_anchors, ps=ps, person="a", **kw)

    party = [local(SAT, 2.0, BAR, plus=k) for k in range(40)]
    vacation = [local(FRI, 11.0, BAR, plus=60 * k) for k in range(40)]
    ordinary = [local(d, 2.0) for d in days_before(FRI, 6)] + [local(d, 12.0, WORK) for d in weekdays_before(FRI, 5)]
    now = local(FRI, 3.0).utc_epoch
    oldest = local(FRI - dt.timedelta(days=90), 3.0, BAR)
    lat, lon, dlat, dlon = pgh.decode_exactly(cell(HOME, 7))
    out += [
        infer("nights and weekdays are counted, not photos", ordinary + party + vacation),
        infer("05:59 is night", [local(FRI, 3.0)] + [local(d, 5.99, BAR) for d in days_before(THU, 2)]),
        infer("06:00 is not", [local(FRI, 3.0)] + [local(d, 6.0, BAR) for d in days_before(THU, 2)]),
        infer(
            "10:00 is work",
            [local(FRI, 3.0), local(FRI, 12.0, WORK)] + [local(d, 10.0, BAR) for d in weekdays_before(THU, 2)],
        ),
        infer(
            "16:00 is not",
            [local(FRI, 3.0), local(FRI, 12.0, WORK)] + [local(d, 16.0, BAR) for d in weekdays_before(THU, 2)],
        ),
        infer(
            "the weekday is local: 15:00 Sunday in Hawaii is Monday UTC",
            [local(FRI, 3.0), local(FRI, 12.0, WORK)]
            + [local(d, 15.0, BAR, HST) for d in (SUN, SUN - dt.timedelta(days=7))],
            now_utc=local(SUN, 23.0, tz=HST).utc_epoch,
        ),
        infer("the window's first second is in it", [oldest], now_utc=now),
        infer("a second earlier is not", [replace(oldest, utc_epoch=oldest.utc_epoch - 1)], now_utc=now),
        infer("nor a second after now", [replace(oldest, utc_epoch=now + 1)], now_utc=now),
        infer("a wider window", [local(FRI - dt.timedelta(days=120), 3.0)], now_utc=now, window_days=180),
        infer(
            "a tie on nights goes to more photos",
            [local(d, 2.0) for d in days_before(FRI, 2)]
            + [local(d, h, BAR) for d in days_before(FRI, 2) for h in (1, 2)],
        ),
        infer("a full tie goes to the smaller geohash", [local(FRI, 2.0), local(FRI, 2.0, BAR)]),
        infer(
            "photos without GPS or a time zone are skipped",
            [replace(local(d, 2.0), lat=None, lon=None) for d in days_before(SAT, 3)]
            + [replace(local(d, 2.0, BAR), tz_offset_s=None) for d in days_before(SAT, 3)]
            + [local(FRI, 2.0, WORK)],
        ),
        infer("no night photo", [local(FRI, 12.0, WORK)]),
        infer("no work photo, no work", [local(FRI, 2.0)]),
        infer(
            "the position is the mean of the winning cell's photos",
            [local(FRI, 2.0, LatLon(lat - dlat / 2, lon)), local(SAT, 2.0, LatLon(lat + dlat / 2, lon - dlon / 2))]
            + [local(SUN, 2.0, BAR)],
        ),
    ]

    def eras(name: str, ps: list[PhotoMeta], current: Anchors | None = None, **kw: Any) -> dict:
        current = current or anchored("a", HOME, WORK)
        return case(name, anchors.home_eras, ps=ps, current=current, now_utc=max(p.utc_epoch for p in ps), **kw)

    first = MOVED - dt.timedelta(days=400)
    stay, back = MOVED - dt.timedelta(days=250), MOVED - dt.timedelta(days=190)
    away = nights(HOME, first - dt.timedelta(days=100), stay, every=7)
    away += nights(FAR, stay + dt.timedelta(days=1), back, every=1, tz=HST) + nights(
        HOME, back + dt.timedelta(days=1), MOVED, every=7
    )
    return out + [
        eras("one home throughout", nights(HOME, first, MOVED, every=4)),
        eras("no night photo: one era", [local(FRI, 12.0, OLD)]),
        eras(
            "a move: the current era starts between the two homes",
            nights(OLD, first, MOVED - dt.timedelta(days=4), every=4, tz=EDT)
            + nights(HOME, MOVED + dt.timedelta(days=3), MOVED + dt.timedelta(days=150), every=4),
        ),
        eras(
            "a move too recent to win a vote still ends the old era",
            nights(OLD, first, MOVED, every=4, tz=EDT)
            + nights(HOME, MOVED + dt.timedelta(days=2), MOVED + dt.timedelta(days=20), every=4),
        ),
        eras(
            "a past home has its own work",
            nights(OLD, first, MOVED - dt.timedelta(days=2), every=4, tz=EDT)
            + [local(d, 12.0, OLD_WORK, EDT) for d in weekdays_before(MOVED - dt.timedelta(days=2), 50)]
            + nights(HOME, MOVED, MOVED + dt.timedelta(days=150), every=4),
        ),
        eras(
            "a home typed in 2 km off is still the current home",
            nights(HOME, first, MOVED, every=4),
            anchored("a", LatLon(HOME.lat + 0.018, HOME.lon), WORK),
        ),
        eras("two months away is no home at min_votes 10", away, min_votes=10),
        eras("but is at min_votes 3", away, min_votes=3),
    ]


def trips_cases() -> list[dict]:
    day_1, day_2 = [key(TAHOE, H), key(TAHOE, H + 2)], [key(TAHOE_2, H + 20)]
    night = (H + 10) * 3600
    shared, apart, moved = homes(*SHARED), homes(*APART), homes(*SHARED, **lived())

    def join(name: str, sessions: list, ps_a: Sequence = (), ps_b: Sequence = (), at: dict = shared, **kw: Any) -> dict:
        return case(name, trips.join_nights, sessions=sessions, homes=at, ps_a=list(ps_a), ps_b=list(ps_b), **kw)

    def carry(name: str, ts: list, ps_a: Sequence = (), ps_b: Sequence = (), at: dict = shared, **kw: Any) -> dict:
        return case(name, trips.tails, trips=ts, homes=at, ps_a=list(ps_a), ps_b=list(ps_b), **kw)

    def assemble(name: str, matched: list, ps_a: Sequence, ps_b: Sequence, now=SHARED, **kw: Any) -> dict:
        return case(
            name,
            trips.assemble,
            matched=matched,
            anchors_a=now[0],
            anchors_b=now[1],
            ps_a=list(ps_a),
            ps_b=list(ps_b),
            **kw,
        )

    lo = (H + 1) * 3600
    start, end = 1_000_000, 1_003_600
    edges = [
        photo("before", start - 1),
        photo("first", start),
        photo("no-gps", start + 60, None),
        photo("last", end - 1),
        photo("after", end),
        photo("no-time", None),
    ]
    w = TripWindow(H * 3600, (H + 1) * 3600, 1, 0, 0, cell(TAHOE), "")
    win_start, win_end = trips.window([key(TAHOE, H)])
    trip_1, visit = [[key(TAHOE, H)]], [[key(B_HOME, H)]]
    return [
        case("nothing matched", trips.sessionize, matched=[]),
        case(
            "a gap of exactly gap_hours stays one session", trips.sessionize, matched=[key(TAHOE, H), key(TAHOE, H + 6)]
        ),
        case("an hour more splits", trips.sessionize, matched=[key(TAHOE, H), key(TAHOE, H + 7)]),
        case("short gaps chain past gap_hours", trips.sessionize, matched=[key(TAHOE, H + 5 * i) for i in range(4)]),
        case(
            "ordered by hour, then geohash, not by key",
            trips.sessionize,
            matched=[
                BucketKey("000000", H + 10),
                BucketKey("zzzzzz", H),
                BucketKey("9qfwm5", H),
                BucketKey("9qfwm4", H),
            ],
        ),
        case("duplicate keys count once", trips.sessionize, matched=[key(TAHOE, H), key(TAHOE, H), key(TAHOE_2, H)]),
        *(
            case(f"cell centre at {p.lat}, {p.lon}", trips.cell_center, k=key(p, H))
            for p in (TAHOE, LatLon(-33.8688, 151.2093), LatLon(64.0, 179.999), LatLon(0.0, 0.0))
        ),
        case("the trip widened by the reach", trips.window, trip=[key(TAHOE, H), key(TAHOE, H + 2)], reach_hours=3),
        case("no reach: the matched hours", trips.window, trip=[key(TAHOE, H)], reach_hours=0),
        case("half-open, any photo with a time", trips.photos_in, start_utc=start, end_utc=end, ps=edges),
        case(
            "backfill counts each partner",
            trips.backfill,
            w=w,
            ps_a=shots("a", 3),
            ps_b=[photo("b-0", H * 3600), photo("b-1", H * 3600 + 5, None), photo("b-2", (H + 1) * 3600)],
        ),
        join("a silent night out of town joins the days", [day_1, day_2]),
        join("A seen back home that night ends the trip", [day_1, day_2], [photo("a", night, HOME)]),
        join("B seen in town ends it too", [day_1, day_2], ps_b=[photo("b", night, IN_TOWN)]),
        join(
            "photos elsewhere or without GPS keep it",
            [day_1, day_2],
            [photo("a", night, NAPA)],
            [photo("b", night, None)],
        ),
        join("sessions in town never join", [[key(IN_TOWN, H)], [key(IN_TOWN, H + 20)]]),
        join("over max_silence_hours without a located photo ends it", [[key(TAHOE, H)], [key(TAHOE, H + 101)]]),
        join(
            "located photos in between keep it",
            [[key(TAHOE, H)], [key(TAHOE, H + 101)]],
            [photo("a-40", lo + 40 * 3600), photo("a-80", lo + 80 * 3600)],
        ),
        join(
            "each partner's silence is timed alone",
            [[key(TAHOE, H)], [key(TAHOE, H + 121)]],
            [photo("a", lo + 40 * 3600)],
            [photo("b", lo + 80 * 3600)],
        ),
        join(
            "the host at home does not end a visit",
            [[key(B_HOME, H)], [key(B_HOME, H + 20)]],
            ps_b=[photo("b", night, B_HOME)],
            at=apart,
        ),
        join(
            "the visitor back home does",
            [[key(B_HOME, H)], [key(B_HOME, H + 20)]],
            [photo("a", night, HOME)],
            at=apart,
        ),
        join("before a move, today's home is just somewhere else", [day_1, day_2], [photo("a", night, HOME)], at=moved),
        join("and the old city is home", [day_1, day_2], [photo("a", night, OLD_CITY)], at=moved),
        carry("A carries the trip into the next days", trip_1, hours("a", 5, 20, 40)),
        carry("so does B", trip_1, ps_b=hours("b", 5, 20, 40)),
        carry("and back before the first match", trip_1, hours("a", -20, -5)),
        carry("24 h then 25 h: stops at the first at tail_gap_hours 24", trip_1, hours("a", 25, 50), tail_gap_hours=24),
        carry("no tail at 23", trip_1, hours("a", 25, 50), tail_gap_hours=23),
        carry("both at 48", trip_1, hours("a", 25, 50), tail_gap_hours=48),
        carry("each partner's run is timed alone", trip_1, hours("a", 10, 50), hours("b", 30, 70)),
        carry(
            "either partner back home stops both",
            trip_1,
            hours("a", 5, 20),
            hours("b", 10, where=HOME) + hours("b", 25),
        ),
        carry("GPS-less photos neither carry it", trip_1, hours("a", 5, 20, where=None)),
        carry("nor stop it", trip_1, hours("a", 5, 20), hours("b", 10, where=None)),
        carry("a host at home does not carry a visit", visit, ps_b=hours("b", 5, 20, where=B_HOME), at=apart),
        carry("the visitor does", visit, hours("a", 5, 20, where=B_HOME), at=apart),
        carry("until back home", visit, hours("a", 5, 20, where=B_HOME) + hours("a", 10, where=HOME), at=apart),
        carry("in town: no tails", [[key(IN_TOWN, H)]], hours("a", 5, 20)),
        carry("tail_gap_hours 0: off", trip_1, hours("a", 5, 20, 40), tail_gap_hours=0),
        carry(
            "neighbouring tails stop 2 x reach apart",
            [[key(TAHOE, H)], [key(TAHOE, H + 200)]],
            hours("a", 10, 30, 50, 70, 90, 110),
            hours("b", 110, 130, 150, 170, 190),
        ),
        assemble("home is never a trip", [key(HOME, H), key(WORK, H + 1)], shots("a", 20), shots("b", 20)),
        assemble("home buckets never join a trip", [key(HOME, H - 2), key(TAHOE, H)], shots("a", 3), shots("b", 2)),
        assemble("nights join into one trip", day_1 + day_2, shots("a", 3), shots("b", 2)),
        assemble("in town", [key(IN_TOWN, H)], shots("a", 5), []),
        assemble("A visiting B", [key(B_HOME, H)], shots("a", 5), [], APART),
        assemble(
            "out of town and in both cities",
            [key(TAHOE, H), key(HOME, H + 1), key(B_HOME, H + 2)],
            shots("a", 5),
            [],
            APART,
        ),
        assemble(
            "told they live together, a visit is home",
            [key(B_HOME, H)],
            shots("a", 3),
            shots("b", 2),
            (anchored("a", HOME, shared_home=True), APART[1]),
        ),
        assemble(
            "the two files disagree on shared_home",
            [key(TAHOE, H)],
            [],
            [],
            (anchored("a", HOME, shared_home=True), anchored("b", HOME, shared_home=False)),
        ),
        assemble(
            "representative: the out-of-town cell with the most hours",
            [key(IN_TOWN, H + i) for i in range(3)] + [key(TAHOE, H + 3)],
            shots("a", 5),
            [],
        ),
        assemble("representative: on a tie, the earlier", [key(TAHOE, H + 1), key(TAHOE_2, H)], shots("a", 5), []),
        assemble("5 photos across both devices: a trip", [key(TAHOE, H)], shots("a", 3), shots("b", 2)),
        assemble("4: not", [key(TAHOE, H)], shots("a", 2), shots("b", 2)),
        assemble("one partner alone can carry it", [key(TAHOE, H)], shots("a", 5), []),
        assemble("4 at min_photos 4", [key(TAHOE, H)], shots("a", 2), shots("b", 2), min_photos=4),
        assemble(
            "backfill takes what one partner shot alone, GPS or not",
            [key(TAHOE, H)],
            [
                photo("a-first", win_start),
                photo("a-last", win_end - 1),
                photo("a-early", win_start - 1),
                photo("a-late", win_end),
            ],
            [photo("b-gps", H * 3600 + 600), photo("b-0", H * 3600 + 900, None), photo("b-1", H * 3600 + 960, None)],
            tail_gap_hours=0,
        ),
        assemble(
            "a tail widens the window, and backfill counts it",
            [key(TAHOE, H)],
            hours("a", 0, 20, 21) + hours("a", 22, where=None),
            hours("b", 0),
        ),
        assemble("a reach over half the gap is refused", [key(TAHOE, H)], [], [], gap_hours=4, reach_hours=3),
        assemble("a day at a home you have since left", [key(OLD_CITY, H)], shots("a", 3), shots("b", 2), **lived()),
        assemble("without a home history, it is a trip", [key(OLD_CITY, H)], shots("a", 3), shots("b", 2)),
        assemble("a trip while living in the old city", [key(TAHOE, H)], shots("a", 5), [], **lived()),
        assemble("a visit to the city you later moved to", [key(HOME, H)], shots("a", 5), [], **lived()),
        assemble(
            "back in the old city after the move", [key(OLD_CITY, MOVE + 10)], shots("a", 5, MOVE + 10), [], **lived()
        ),
        assemble("home now is neither", [key(HOME, MOVE + 10)], shots("a", 5, MOVE + 10), [], **lived()),
        assemble(
            "old-home days never join across nights",
            [key(OLD_CITY, H), key(OLD_CITY, H + 20)],
            shots("a", 5, H) + shots("a", 5, H + 20),
            [],
            **lived(),
        ),
        assemble(
            "where an old-home day would overlap a trip, the trip wins",
            [key(TAHOE, H), key(OLD_CITY, H + 5)],
            shots("a", 5, H) + shots("a", 5, H + 5),
            [],
            **lived(),
        ),
        assemble("an old-home day needs min_photos too", [key(OLD_CITY, H)], shots("a", 4), [], **lived()),
    ]


# the whole spike on one couple


def pipeline(
    ps_a: Sequence[PhotoMeta],
    ps_b: Sequence[PhotoMeta],
    salt: bytes,
    *,
    window_days: int = 90,
    gap_hours: int = trips.GAP_HOURS,
    reach_hours: int = trips.REACH_HOURS,
    city_km: float = trips.CITY_KM,
    max_silence_hours: int = trips.MAX_SILENCE_HOURS,
    tail_gap_hours: int = trips.TAIL_GAP_HOURS,
    min_photos: int = trips.MIN_PHOTOS,
) -> dict[str, Any]:
    """As `make skeleton` runs it: each partner's filters, anchors over the last window_days and home
    history, then A expanded and B raw, salted, intersected, mapped back on A's side, and trips."""
    side: dict[str, dict[str, Any]] = {}
    for person, raw in (("a", ps_a), ("b", ps_b)):
        ps, dropped = filters.apply_all(list(raw))
        now = max(p.utc_epoch for p in ps)
        an = anchors.infer_anchors(ps, person=person, now_utc=now, window_days=window_days)
        side[person] = {"kept": ps, "dropped": dropped, "anchors": an, "eras": anchors.home_eras(ps, an, now_utc=now)}
    a, b = side["a"], side["b"]
    own_a = buckets.own_keys(a["kept"], expanded=True)
    m = matching.match(
        buckets.salted_set(own_a, salt), buckets.salted_set(buckets.own_keys(b["kept"], expanded=False), salt)
    )
    keys = buckets.matched_keys(own_a, m, salt)
    ws = trips.assemble(
        sorted(keys),
        a["anchors"],
        b["anchors"],
        ps_a=a["kept"],
        ps_b=b["kept"],
        gap_hours=gap_hours,
        reach_hours=reach_hours,
        city_km=city_km,
        max_silence_hours=max_silence_hours,
        tail_gap_hours=tail_gap_hours,
        min_photos=min_photos,
        eras_a=a["eras"],
        eras_b=b["eras"],
    )
    return {"a": a, "b": b, "matched": keys, "trips": ws}


def at_tahoe(located_a: int, located_b: int) -> dict[str, list[PhotoMeta]]:
    """A week of nights at home and of days at work each, then ten photos each together at Tahoe
    at noon on a Friday (hour H), the first `located_*` of them with GPS."""
    day = dt.date(2026, 7, 10)
    out = {}
    for person, located in (("a", located_a), ("b", located_b)):
        before = [local(d, 2.0) for d in days_before(day, 7)]
        before += [local(d, 12.0, WORK) for d in weekdays_before(day - dt.timedelta(days=1), 5)]
        out[f"ps_{person}"] = [replace(p, asset_id=f"{person}-{p.asset_id}") for p in before] + [
            photo(f"{person}-tahoe-{i}", H * 3600 + 60 * i, TAHOE if i < located else None) for i in range(10)
        ]
    return out


def pipeline_cases() -> list[dict]:
    data = synth.generate()
    return [
        case("the synthetic couple (make skeleton)", pipeline, ps_a=data.a, ps_b=data.b, salt=SALT),
        case("together at Tahoe", pipeline, **at_tahoe(10, 10), salt=SALT),
        case("GPS on A's side only: no match, no trip", pipeline, **at_tahoe(10, 0), salt=SALT),
        case("GPS on B's side only: no match, no trip", pipeline, **at_tahoe(0, 10), salt=SALT),
        case("one located photo of B's finds it, and backfill brings the rest", pipeline, **at_tahoe(10, 1), salt=SALT),
        case("one of A's does too", pipeline, **at_tahoe(1, 10), salt=SALT),
    ]


CASES: dict[str, Callable[[], list[dict]]] = {
    "project": project_cases,
    "filters": filters_cases,
    "buckets": buckets_cases,
    "matching": matching_cases,
    "commute": commute_cases,
    "anchors": anchors_cases,
    "trips": trips_cases,
    "pipeline": pipeline_cases,
}


def files() -> dict[str, str]:
    """File name -> its text."""
    out = {}
    for name, cases in CASES.items():
        consts = constants(importlib.import_module(f"photoquiz.{name}")) if name != "pipeline" else {}
        out[f"{name}.json"] = dumps({"_": NOTE, "constants": consts, "cases": cases()}) + "\n"
    return out


if __name__ == "__main__":
    for name, text in files().items():
        (OUT / name).write_text(text)
        print(f"{OUT.name}/{name}: {text.count(chr(10))} lines, {len(text) // 1024} KiB")
